### ISSUE TITLE
2024-01-08 출근

### ISSUE THREAD

**Issue by walnutpie314** [walnutpie314/Multiplayer#1]

**Comment by walnutpie314** [comment]
@jongfeel 2023-01-02 ~ 2023-01-05 서울에 집 구하러 올라갈 예정

기간 내에 최대한 집을 빨리 구하는 것이 목표입니다!

**Comment by jongfeel** [comment]
면접 결과가 오늘 나오셨군요.
우선 오퍼 받으신건 축하드리고, 앞으로 회사 생활 잘 하시면 좋겠습니다.

그러면 오늘은 지났고, 집 구하는 기간 제외해서 프로젝트 할 시간을 정해 주시고 그 시간대로 진행하시면 좋겠습니다.
